### ISSUE TITLE
`GetTextureDimensions` second argument is broken

### ISSUE THREAD

**Issue by Hdt80bro** [FAForever/FA-Binary-Patches#12]
`width, height GetTextureDimensions(filename, border = 1)`

The documentation says that the second argument defaults to `1`, but passing anything in makes it always claim that it wants an integer and was given a table.

**Comment by KionX** [comment]
The parameter is broken. In working condition, it changes the result to size+border*2.
I don't see the point in fixing it.

**Comment by Hdt80bro** [comment]
Very well
