### ISSUE TITLE
Allow templates to snap (to resources)

### ISSUE THREAD

**Issue by Garanas** [FAForever/FA-Binary-Patches#28]
### Description

When you try to build an extractor or a hydrocarbon plant your build preview will snap to the resource deposit. This radius of behavior can be changed via the console command`ui_ExtractSnapTolerance` .

When you enable a template preview via `SetActiveBuildTemplate` the snap behavior is disabled, even though the build mode is still set to an extractor or a hydrocarbon plant. 

### Suggested change

Do not disable the snap behavior. The snap behavior should still apply using the context of the unit that you entered build mode for, unrelated to the units in the template.

### What we can do with it

This would allow us to extend the [Context based templates](https://github.com/FAForever/fa/pull/5310) feature. By allowing snapping to work with build templates it will be easier to place down templates that include extractors, storages and even fabricators.

**Comment by 4z0t** [comment]
Do we close this? Or hydro snap is needed too? :D

**Comment by Garanas** [comment]
@4z0t if you use [closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in the pull request then the issue is linked and closes automatically when the pull request is merged in
