### ISSUE TITLE
Possibility to define new 'MotionTypes' under 'Physics' in the unit blueprints

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/FA-Binary-Patches#71]
I have no knowledge of this, so if this is request is unreasonable, feel free to close this.

The MotionTypes currently available:

    RULEUMT_Air                = {Air = 16},
    RULEUMT_Amphibious         = LayerCaps[ 3 --[[0x01 | 0x02]] ],
    RULEUMT_AmphibiousFloating = LayerCaps[ 9 --[[0x01 | 0x08]] ],
    RULEUMT_Biped              = LayerCaps[ 0x01 ],
    RULEUMT_Land               = LayerCaps[ 0x01 ],
    RULEUMT_Hover              = LayerCaps[ 9 --[[0x01 | 0x08]] ],
    RULEUMT_Water              = LayerCaps[ 0x08 ],
    RULEUMT_SurfacingSub       = LayerCaps[ 12 --[[0x04 | 0x08]] ],
    RULEUMT_None               = {Sub = 4, Land = 1, Seabed = 2, Water = 8},
    
These are defined in the engine and we cannot change them, or add new ones at the moment.

**Comment by Garanas** [comment]
I'm fairly certain that this is out of scope. How units behave pathing-wise is woven into the engine.

**Comment by 4z0t** [comment]
Even if we could, they are mapped somewhere else 
![image](https://github.com/user-attachments/assets/8afec938-bc33-4345-8aec-07e8e1acc858)
